apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpa-predictor
spec:
  replicas: 2 # Two replicas, disaster prevention
  selector:
    matchLabels:
      app: cpa-predictor
  template:
    metadata:
      labels:
        app: cpa-predictor
    spec:
      containers:
      - name: cpa-predictor
        image: diasmig/cpa-predictor:v2

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: cpa-predictor-service
spec:
  type: NodePort
  selector:
    app: cpa-predictor
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
